apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-10-22T10:22:44Z"
  generation: 1
  labels:
    k8s-app: api
  name: api
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/api
  uid: f7f68744-09a6-4323-97eb-f3441243646d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: api
      name: api
    spec:
      containers:
      - image: waeltken/fabmedical-content-api:latest
        env:
          - name: MONGODB_CONNECTION
            valueFrom:
              secretKeyRef:
                name: cosmosdb
                key: db
        imagePullPolicy: Always
        name: api
        resources:
          requests:
            cpu: "1"
            memory: 128Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-10-22T10:22:44Z"
    lastUpdateTime: "2020-10-22T10:22:48Z"
    message: ReplicaSet "api-7cdbb47b44" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-10-22T10:25:39Z"
    lastUpdateTime: "2020-10-22T10:25:39Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
